name = "QuantumOptimalControl"
uuid = "02a92613-dda7-4fef-8fd4-baed6d44f5e0"
authors = ["olof3 <olof3@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DiffEqSensitivity = "41bf760c-e81c-5289-8e54-58b1f1f8abe2"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
